# Students Mark Analysis

1. Average by Subject and Students
2. Highest and lowest per subject 
3. Overall class toppers
4. Pass count per subject 
5. which subject is difficult
6. Ranking students

In [3]:
import numpy as np

np.random.seed(40)
marks = np.random.randint(10, 101, size= (20,5))
print(marks)

[[ 80  17  47  66  60]
 [ 75  22  81  29  41]
 [ 84  65  93  69  83]
 [ 59  63  83  18  62]
 [ 40  89  24  68  84]
 [ 32  13  81  65  93]
 [ 38  23  47  92  60]
 [ 89  77  40  70  54]
 [ 56  97  53  45  41]
 [ 92  15  90  75  17]
 [ 51  98  35  93  68]
 [ 80  67  67  93  95]
 [ 46  73  84  98  10]
 [ 11  43  62  82  67]
 [ 44  24  88  81  66]
 [ 87  96  94  92  22]
 [100  83  37  10  31]
 [ 42  61  60  30  51]
 [ 88  65  57  53  86]
 [ 39  55  17  20  71]]


In [6]:
Avg_by_subject = np.mean(marks, axis =0)
print("Average in subjects : ",Avg_by_subject)

Avg_by_students = np.mean(marks, axis= 1)
print("Average of students : ", Avg_by_students)

Average in subjects :  [61.65 57.3  62.   62.45 58.1 ]
Average of students :  [54.  49.6 78.8 57.  61.  56.8 52.  66.  58.4 57.8 69.  80.4 62.2 53.
 60.6 78.2 52.2 48.8 69.8 40.4]


In [8]:
Highest_mark = np.max(marks, axis=0)
print("Max mark per subjects : ",Highest_mark)

Lowest_mark = np.min(marks ,axis= 0)
print("Min mark per subject : ", Lowest_mark)

Max mark per subjects :  [100  98  94  98  95]
Min mark per subject :  [11 13 17 10 10]


In [ ]:
#Overall topper

total_marks = np.sum(marks , axis =1) 
print("Total marks by students : ",total_marks)

topper = np.argmax(total_marks) #argmax pick the position of max value
print(f"Topper of the class is {topper} with overall mark of {total_marks[topper]}")

Total marks by students :  [270 248 394 285 305 284 260 330 292 289 345 402 311 265 303 391 261 244
 349 202]
Topper of the class is 11 with overall mark of 402


In [12]:
# pass count

pass_fail = marks >= 40

pass_count = np.sum(pass_fail, axis= 0)
print("Count of pass: ", pass_count)

Count of pass:  [16 14 16 15 16]


In [16]:
#difficult subject

Avg_by_subject = np.mean(marks, axis=0)
print("Average marks in subjects", Avg_by_subject)

difficult_subject = np.argmin(Avg_by_subject)
print("Difficult subject is", difficult_subject, "with avg of mark of", Avg_by_subject[difficult_subject])

Average marks in subjects [61.65 57.3  62.   62.45 58.1 ]
Difficult subject is 1 with avg of mark of 57.3


In [21]:
#Ranks 

ranks = np.argsort(-total_marks) # - helps in arrange for descending order
print(f"First Rank of the class is , {ranks [0]}")
print(f"Top 5 of the class is, {ranks [:5]}")

First Rank of the class is , 11
Top 5 of the class is, [11  2 15 18 10]
