# Numpy - Numerical Python. It allows 1D,2D, 3D ,......,10D it supports multi dimensional arrays

# Numpy is faster than python List

# we can calculate the different Array without any looping.

# Numpy is for mathematical calculation, it supports linear algebra & statistics defaultly

# Used in Data Engineering, Ml, Ai - many libraries like pandas, scipy, tensorflow depend on numpy

In [4]:
import numpy as np

print(np.__version__)

1.26.4


In [ ]:
#Single dimesnion array  vs list

arr = np.array([10,20,30,40,50]) 
print("This is Numpy output",arr)   #numpy output dont come with comma "," because for mathematical operation we dont need comma.

List = [10,20,30]
print("This is list output",List)

This is Numpy output [10 20 30 40 50]
This is list output [10, 20, 30]


In [11]:
arr2D = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2D ,"\n")
print(type(arr2D))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

<class 'numpy.ndarray'>


In [ ]:
#Print shape of Array, output is in number of rows and columns

print(arr.shape)
print(arr2D.shape)  

# Print the size of elements present inside the array

print(arr2D.size)

#Checking dimension of array

print(arr.ndim)
print(arr2D.ndim)

#Finding data type inside the array

print(arr.dtype) 


(5,)
(2, 5)
10
1
2
int32


In [ ]:
# If one value is change to float then ever int is convert to float

arr2D = np.array([[1,2,3,4,5],[6.0,7,8,9,10]])  #Actual data int -> float is 1 value means convert to float -> str is 1 value means everything convert to string
print(arr2D.dtype)

#There is float inside data, but we actually need  int only means we can easily convert float to int

arr2D = np.array([[1,2,3,4,5],[6.0,7,8,9,10]], dtype=int) #-> explicit the data type
print(arr2D.dtype)


float64
int32


In [ ]:
#using numpy we can easily fillup with zero,1 or any constant values

print(np.zeros((2,3))) #output is in float, because numpy default dtype is float
print(np.ones((2,3)))

print(np.full((2,3), 10)) #full helps to setup constant values

print(np.empty((2,3))) #create empty value, retrieve the last data which stored in memory, it is not fixed

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[10 10 10]
 [10 10 10]]
[[1. 1. 1.]
 [1. 1. 1.]]


# Array Operation

In [36]:
a= np.array([1,2,3])
b= np.array([10,20,30])

print(a+b)
print(a-b)
print(a*b)
print(b//a)

[11 22 33]
[ -9 -18 -27]
[10 40 90]
[10 10 10]


In [ ]:
# Constant value calculation also we can do

a= np.array([1,2,3])
b= 5                     #internally create [5,5,5] in virtual memory

print(a+b)

[6 7 8]


In [46]:
# with multi dim

a= np.array([1,2,3])
b= np.array([[10,20,30],[40,50,60],[70,80,90]])

print(a+b)

[[11 22 33]
 [41 52 63]
 [71 82 93]]


# Aggregation in numpy -> is the process of summary statistics (sum, min, max, mean, etc) over an array

In [55]:
a= np.array([1,2,3,4,5])
print("Sum :", np.sum(a))
print("Average :", np.mean(a))
print("Middle value :", np.median(a))
print("Min value :", np.min(a))
print("Max value :", np.max(a))


Sum : 15
Average : 3.0
Middle value : 3.0
Min value : 1
Max value : 5


# Variance finding in statistics

1. In case variance is higher it is un predicctable.
2. If variance is lower it is easy for the prediction

Formula:

variance = 1/N sum(x - mean)²

# Standard deviation is the square root of variance

std = √1/N sum(x - mean)²

In [57]:
print("Varaince :" ,np.var(a))
print("Standard_deviation :", np.std(a))

Varaince : 2.0
Standard_deviation : 1.4142135623730951


In [60]:
arr = np.array([[1,2,3],[3,6,8]])

print("Sum :", np.sum(arr))
print("Sum Columns :", np.sum(arr , axis = 0))
print("Sum Rows :", np.sum(arr, axis = 1))

Sum : 23
Sum Columns : [ 4  8 11]
Sum Rows : [ 6 17]


In [61]:
#Condition in numpy

arr = np.array([[1,2,3],[3,6,8]])
print("Sum :", np.sum(arr[arr >2 ]))


Sum : 20


# Indexing -> Access individual Elements
# Slicing -> Extracting sub arrays using  start : stop  : step
# Boolean Indexing -> filter based condition
# Filtering -> select specific elements directly using conditions

In [ ]:
#Indexing

a= np.array([1,2,3,4,5])
print(a[3])

a2D =np.array([[1,2,3],[3,6,8]])
print("Accessing 6",a2D[1][1])

4
6


In [ ]:
#Slicing -> start : stop  : step

print("Retrieve 2 & 3 :", a[1:3])

print(a[::]) # start to end all data
print(a[::-1]) #reverse

Retrieve 2 & 3 : [2 3]
[1 2 3 4 5]
[5 4 3 2 1]


In [90]:
# Slicing in multi dim

a2D =np.array([[1,2,3,4,5,7],[3,6,8,9,12,10]])

print("Access all multi dim",a2D[0 :2])

print("Retrieve 6 & 8 :", a2D[1:2 , 1:3])

print("Step by step :", a2D[0:2:2 , 1:6:2])

Access all multi dim [[ 1  2  3  4  5  7]
 [ 3  6  8  9 12 10]]
Retrieve 6 & 8 : [[6 8]]
Step by step : [[2 4 7]]


# Boolean Indexing

In [95]:
a= np.array([1,2,3,4,5])

a_bool = a > 2    
print(a_bool)

print(a[a_bool])

[False False  True  True  True]
[3 4 5]


# Filtering

In [ ]:
#Direct conditon apply

a= np.array([1,2,3,4,5])

print(a[a > 2]) #returns greater than 2 

print(a [ a % 2 == 0]) #print even numbers

[3 4 5]
[2 4]


In [101]:
#Filtering with multiple conditions

a2D =np.array([[1,2,3,4,5,7],[3,6,8,9,12,10]])
print(a2D[ (a2D > 2) & (a2D < 10)])


[3 4 5 7 3 6 8 9]


# Reshaping -> change the shape of the array (changes affect orginal data)

# Ravel -> change multi dimensional array to single dimensional ( Once we update/modify the data it will refelect here)

# Flatten -> similar to Ravel, but returns a copy (It do modify on copy data dont affect original data)

# hstack -> joins array horizontally (along axis 1) column level

# vstack -> joins array vertically (along axis 0) row level

# Concatenate -> can concatenate along any axis

# Transpose -> swaps rows to columns. Using ".T" we can access

In [ ]:
#Reshaping

arr_1D = np.array([10,20,30,40,50,60])
print("This is original array", arr_1D)

reshaped = arr_1D.reshape(2,3)
print("Reshaped Array :", reshaped)

reshaped[0][0] = 70             #changing value in reshaped affect the original data also.
print("Reshaped :", reshaped)

print("Orginal Array", arr_1D)

This is original array [10 20 30 40 50 60]
Reshaped Array : [[10 20 30]
 [40 50 60]]
Reshaped : [[70 20 30]
 [40 50 60]]
Orginal Array [70 20 30 40 50 60]


In [110]:
 # Ravel -> Flatten the dimension into single

arr_2D = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print("Original Before ravel:", arr_2D)

ravel = arr_2D.ravel()
print("copy of arr_2D :", ravel) # make the 2D into 1D 
ravel[0] = 10                    #once changes made in the copy refelect in original also
print ("Updated ravel :", ravel)

print("original after ravel :", arr_2D)

Original Before ravel: [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
copy of arr_2D : [ 1  2  3  4  5  6  7  8  9 10 11 12]
Updated ravel : [10  2  3  4  5  6  7  8  9 10 11 12]
original after ravel : [[10  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [112]:
# Flatten -> same work as ravel, but never affect original data

arr_2D = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print("Original Before Flatten:", arr_2D)

flat = arr_2D.flatten()
print("copy of arr_2D :", flat)

flat[1]= 20
print("Updated flatten :", flat)

print("Original data after updation :", arr_2D)

Original Before Flatten: [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
copy of arr_2D : [ 1  2  3  4  5  6  7  8  9 10 11 12]
Updated flatten : [ 1 20  3  4  5  6  7  8  9 10 11 12]
Original data after updation : [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [125]:
# hstack works in columnwise

a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

print("Original data :", a1,a2)
print("After hstack :",np.hstack([a1, a2])) # now its 6 columns

# vstack works in rowwise

print("After vstack :", np.vstack([a1,a2]))

#Concatenate -> it is flexible and we have the control to decide whether it is row or column

a1 = np.array([[1,2],[3,4]])
a2 = np.array([[4,5],[6,7]])

print("After Concatenate :", np.concatenate([a1,a2]))

Original data : [1 2 3] [4 5 6]
After hstack : [1 2 3 4 5 6]
After vstack : [[1 2 3]
 [4 5 6]]
After Concatenate : [[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [129]:
# Transpose -> column to row, row to column

a1 = np.array([[1,2,3], [4,5,6]])

print("Swap :", a1 .T)

print("Reverse Swap :", a1 .T.T )


Swap : [[1 4]
 [2 5]
 [3 6]]
Reverse Swap : [[1 2 3]
 [4 5 6]]


# Random number -> rand() generates random float between 0 and 1 

# randint -> Generate random integers

# Random Distributions 

1. Normal Distribution
2. Uniform Distribution
3. Binominal Distribution

In [ ]:
print(np.random.rand()) # Generates number between 0 to 1

0.39521685557492503
